version: '3'
networks:
    RUBY:
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - RUBY
  app:
    build: .
    container_name: ruby
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - RAKE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/myapp
    depends_on:
      - db
    networks:
      - RUBY
volumes:
  postgres_data: {}
