version: '3'
networks:
    RUBY:
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - RUBY
  app:
    build: .
    container_name: ruby
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/cartaomaispet
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - RUBY
volumes:
  postgres:
