version: '3'
networks:
    RUBY:
services:
  db:
    container_name: postgres
    image: postgres
    env_file: .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - RUBY
  app:
    build: .
    container_name: ruby
    environment:
     RAILS_ENV: production
    env_file: .env
    volumes:
      - .:/cartaomaispet
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - RUBY
volumes:
  postgres:
